/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalArduinoParser;
import org.xtext.example.mydsl.services.ArduinoGrammarAccess;

public class ArduinoParser extends AbstractAntlrParser {

	@Inject
	private ArduinoGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalArduinoParser createParser(XtextTokenStream stream) {
		return new InternalArduinoParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ArduinoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ArduinoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
