/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.arduino.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.arduino.ArduinoPackage;
import org.xtext.example.mydsl.arduino.component_state;
import org.xtext.example.mydsl.arduino.components;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>components</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.arduino.impl.componentsImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.arduino.impl.componentsImpl#getConnectors <em>Connectors</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.arduino.impl.componentsImpl#getComponent_state <em>Component state</em>}</li>
 * </ul>
 *
 * @generated
 */
public class componentsImpl extends MinimalEObjectImpl.Container implements components
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getConnectors() <em>Connectors</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConnectors()
   * @generated
   * @ordered
   */
  protected EList<String> connectors;

  /**
   * The cached value of the '{@link #getComponent_state() <em>Component state</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComponent_state()
   * @generated
   * @ordered
   */
  protected EList<component_state> component_state;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected componentsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ArduinoPackage.Literals.COMPONENTS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ArduinoPackage.COMPONENTS__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getConnectors()
  {
    if (connectors == null)
    {
      connectors = new EDataTypeEList<String>(String.class, this, ArduinoPackage.COMPONENTS__CONNECTORS);
    }
    return connectors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<component_state> getComponent_state()
  {
    if (component_state == null)
    {
      component_state = new EObjectContainmentEList<component_state>(component_state.class, this, ArduinoPackage.COMPONENTS__COMPONENT_STATE);
    }
    return component_state;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ArduinoPackage.COMPONENTS__COMPONENT_STATE:
        return ((InternalEList<?>)getComponent_state()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ArduinoPackage.COMPONENTS__NAME:
        return getName();
      case ArduinoPackage.COMPONENTS__CONNECTORS:
        return getConnectors();
      case ArduinoPackage.COMPONENTS__COMPONENT_STATE:
        return getComponent_state();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ArduinoPackage.COMPONENTS__NAME:
        setName((String)newValue);
        return;
      case ArduinoPackage.COMPONENTS__CONNECTORS:
        getConnectors().clear();
        getConnectors().addAll((Collection<? extends String>)newValue);
        return;
      case ArduinoPackage.COMPONENTS__COMPONENT_STATE:
        getComponent_state().clear();
        getComponent_state().addAll((Collection<? extends component_state>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ArduinoPackage.COMPONENTS__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ArduinoPackage.COMPONENTS__CONNECTORS:
        getConnectors().clear();
        return;
      case ArduinoPackage.COMPONENTS__COMPONENT_STATE:
        getComponent_state().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ArduinoPackage.COMPONENTS__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ArduinoPackage.COMPONENTS__CONNECTORS:
        return connectors != null && !connectors.isEmpty();
      case ArduinoPackage.COMPONENTS__COMPONENT_STATE:
        return component_state != null && !component_state.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", connectors: ");
    result.append(connectors);
    result.append(')');
    return result.toString();
  }

} //componentsImpl
