/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.arduino.ui.internal.ArduinoActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ArduinoExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ArduinoActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ArduinoActivator activator = ArduinoActivator.getInstance();
		return activator != null ? activator.getInjector(ArduinoActivator.ORG_XTEXT_EXAMPLE_MYDSL_ARDUINO) : null;
	}

}
