/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.arduino;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.arduino.ArduinoFactory
 * @model kind="package"
 * @generated
 */
public interface ArduinoPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "arduino";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Arduino";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "arduino";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ArduinoPackage eINSTANCE = org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.arduino.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.arduino.impl.ModelImpl
   * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Components</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__COMPONENTS = 0;

  /**
   * The feature id for the '<em><b>Connection</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CONNECTION = 1;

  /**
   * The feature id for the '<em><b>Behavior</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__BEHAVIOR = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.arduino.impl.componentsImpl <em>components</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.arduino.impl.componentsImpl
   * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getcomponents()
   * @generated
   */
  int COMPONENTS = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTS__NAME = 0;

  /**
   * The feature id for the '<em><b>Connectors</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTS__CONNECTORS = 1;

  /**
   * The feature id for the '<em><b>Component state</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTS__COMPONENT_STATE = 2;

  /**
   * The number of structural features of the '<em>components</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENTS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.arduino.impl.component_stateImpl <em>component state</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.arduino.impl.component_stateImpl
   * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getcomponent_state()
   * @generated
   */
  int COMPONENT_STATE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_STATE__NAME = 0;

  /**
   * The number of structural features of the '<em>component state</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_STATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.arduino.impl.minImpl <em>min</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.arduino.impl.minImpl
   * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getmin()
   * @generated
   */
  int MIN = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIN__NAME = 0;

  /**
   * The number of structural features of the '<em>min</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.arduino.impl.maxImpl <em>max</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.arduino.impl.maxImpl
   * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getmax()
   * @generated
   */
  int MAX = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAX__NAME = 0;

  /**
   * The number of structural features of the '<em>max</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAX_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.arduino.impl.connectionImpl <em>connection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.arduino.impl.connectionImpl
   * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getconnection()
   * @generated
   */
  int CONNECTION = 5;

  /**
   * The feature id for the '<em><b>Component</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION__COMPONENT = 0;

  /**
   * The feature id for the '<em><b>Wiring</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION__WIRING = 1;

  /**
   * The number of structural features of the '<em>connection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.arduino.impl.componentImpl <em>component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.arduino.impl.componentImpl
   * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getcomponent()
   * @generated
   */
  int COMPONENT = 6;

  /**
   * The feature id for the '<em><b>Components</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__COMPONENTS = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__NAME = 1;

  /**
   * The number of structural features of the '<em>component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.arduino.impl.wiringImpl <em>wiring</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.arduino.impl.wiringImpl
   * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getwiring()
   * @generated
   */
  int WIRING = 7;

  /**
   * The feature id for the '<em><b>Src</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIRING__SRC = 0;

  /**
   * The feature id for the '<em><b>Src port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIRING__SRC_PORT = 1;

  /**
   * The feature id for the '<em><b>Tar</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIRING__TAR = 2;

  /**
   * The feature id for the '<em><b>Tar port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIRING__TAR_PORT = 3;

  /**
   * The number of structural features of the '<em>wiring</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIRING_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.arduino.impl.behaviorImpl <em>behavior</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.arduino.impl.behaviorImpl
   * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getbehavior()
   * @generated
   */
  int BEHAVIOR = 8;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR__STATES = 0;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR__TRANSITIONS = 1;

  /**
   * The number of structural features of the '<em>behavior</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.arduino.impl.transitionImpl <em>transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.arduino.impl.transitionImpl
   * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#gettransition()
   * @generated
   */
  int TRANSITION = 9;

  /**
   * The feature id for the '<em><b>Src state</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__SRC_STATE = 0;

  /**
   * The feature id for the '<em><b>Tar state</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__TAR_STATE = 1;

  /**
   * The feature id for the '<em><b>Transition effect</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__TRANSITION_EFFECT = 2;

  /**
   * The number of structural features of the '<em>transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.arduino.impl.transition_effectImpl <em>transition effect</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.arduino.impl.transition_effectImpl
   * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#gettransition_effect()
   * @generated
   */
  int TRANSITION_EFFECT = 10;

  /**
   * The feature id for the '<em><b>Microseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_EFFECT__MICROSECONDS = 0;

  /**
   * The number of structural features of the '<em>transition effect</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_EFFECT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.arduino.impl.stateImpl <em>state</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.arduino.impl.stateImpl
   * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getstate()
   * @generated
   */
  int STATE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__NAME = 0;

  /**
   * The feature id for the '<em><b>Component</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__COMPONENT = 1;

  /**
   * The feature id for the '<em><b>Component state</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__COMPONENT_STATE = 2;

  /**
   * The number of structural features of the '<em>state</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.arduino.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.arduino.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.arduino.Model#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Components</em>'.
   * @see org.xtext.example.mydsl.arduino.Model#getComponents()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Components();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.arduino.Model#getConnection <em>Connection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Connection</em>'.
   * @see org.xtext.example.mydsl.arduino.Model#getConnection()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Connection();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.arduino.Model#getBehavior <em>Behavior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Behavior</em>'.
   * @see org.xtext.example.mydsl.arduino.Model#getBehavior()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Behavior();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.arduino.components <em>components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>components</em>'.
   * @see org.xtext.example.mydsl.arduino.components
   * @generated
   */
  EClass getcomponents();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.arduino.components#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.arduino.components#getName()
   * @see #getcomponents()
   * @generated
   */
  EAttribute getcomponents_Name();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.arduino.components#getConnectors <em>Connectors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Connectors</em>'.
   * @see org.xtext.example.mydsl.arduino.components#getConnectors()
   * @see #getcomponents()
   * @generated
   */
  EAttribute getcomponents_Connectors();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.arduino.components#getComponent_state <em>Component state</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Component state</em>'.
   * @see org.xtext.example.mydsl.arduino.components#getComponent_state()
   * @see #getcomponents()
   * @generated
   */
  EReference getcomponents_Component_state();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.arduino.component_state <em>component state</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>component state</em>'.
   * @see org.xtext.example.mydsl.arduino.component_state
   * @generated
   */
  EClass getcomponent_state();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.arduino.component_state#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.arduino.component_state#getName()
   * @see #getcomponent_state()
   * @generated
   */
  EAttribute getcomponent_state_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.arduino.min <em>min</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>min</em>'.
   * @see org.xtext.example.mydsl.arduino.min
   * @generated
   */
  EClass getmin();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.arduino.min#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.arduino.min#getName()
   * @see #getmin()
   * @generated
   */
  EAttribute getmin_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.arduino.max <em>max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>max</em>'.
   * @see org.xtext.example.mydsl.arduino.max
   * @generated
   */
  EClass getmax();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.arduino.max#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.arduino.max#getName()
   * @see #getmax()
   * @generated
   */
  EAttribute getmax_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.arduino.connection <em>connection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>connection</em>'.
   * @see org.xtext.example.mydsl.arduino.connection
   * @generated
   */
  EClass getconnection();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.arduino.connection#getComponent <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Component</em>'.
   * @see org.xtext.example.mydsl.arduino.connection#getComponent()
   * @see #getconnection()
   * @generated
   */
  EReference getconnection_Component();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.arduino.connection#getWiring <em>Wiring</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Wiring</em>'.
   * @see org.xtext.example.mydsl.arduino.connection#getWiring()
   * @see #getconnection()
   * @generated
   */
  EReference getconnection_Wiring();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.arduino.component <em>component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>component</em>'.
   * @see org.xtext.example.mydsl.arduino.component
   * @generated
   */
  EClass getcomponent();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.arduino.component#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Components</em>'.
   * @see org.xtext.example.mydsl.arduino.component#getComponents()
   * @see #getcomponent()
   * @generated
   */
  EReference getcomponent_Components();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.arduino.component#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.arduino.component#getName()
   * @see #getcomponent()
   * @generated
   */
  EAttribute getcomponent_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.arduino.wiring <em>wiring</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>wiring</em>'.
   * @see org.xtext.example.mydsl.arduino.wiring
   * @generated
   */
  EClass getwiring();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.arduino.wiring#getSrc <em>Src</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Src</em>'.
   * @see org.xtext.example.mydsl.arduino.wiring#getSrc()
   * @see #getwiring()
   * @generated
   */
  EReference getwiring_Src();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.arduino.wiring#getSrc_port <em>Src port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Src port</em>'.
   * @see org.xtext.example.mydsl.arduino.wiring#getSrc_port()
   * @see #getwiring()
   * @generated
   */
  EAttribute getwiring_Src_port();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.arduino.wiring#getTar <em>Tar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Tar</em>'.
   * @see org.xtext.example.mydsl.arduino.wiring#getTar()
   * @see #getwiring()
   * @generated
   */
  EReference getwiring_Tar();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.arduino.wiring#getTar_port <em>Tar port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tar port</em>'.
   * @see org.xtext.example.mydsl.arduino.wiring#getTar_port()
   * @see #getwiring()
   * @generated
   */
  EAttribute getwiring_Tar_port();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.arduino.behavior <em>behavior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>behavior</em>'.
   * @see org.xtext.example.mydsl.arduino.behavior
   * @generated
   */
  EClass getbehavior();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.arduino.behavior#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see org.xtext.example.mydsl.arduino.behavior#getStates()
   * @see #getbehavior()
   * @generated
   */
  EReference getbehavior_States();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.arduino.behavior#getTransitions <em>Transitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transitions</em>'.
   * @see org.xtext.example.mydsl.arduino.behavior#getTransitions()
   * @see #getbehavior()
   * @generated
   */
  EReference getbehavior_Transitions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.arduino.transition <em>transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>transition</em>'.
   * @see org.xtext.example.mydsl.arduino.transition
   * @generated
   */
  EClass gettransition();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.arduino.transition#getSrc_state <em>Src state</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Src state</em>'.
   * @see org.xtext.example.mydsl.arduino.transition#getSrc_state()
   * @see #gettransition()
   * @generated
   */
  EReference gettransition_Src_state();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.arduino.transition#getTar_state <em>Tar state</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Tar state</em>'.
   * @see org.xtext.example.mydsl.arduino.transition#getTar_state()
   * @see #gettransition()
   * @generated
   */
  EReference gettransition_Tar_state();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.arduino.transition#getTransition_effect <em>Transition effect</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Transition effect</em>'.
   * @see org.xtext.example.mydsl.arduino.transition#getTransition_effect()
   * @see #gettransition()
   * @generated
   */
  EReference gettransition_Transition_effect();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.arduino.transition_effect <em>transition effect</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>transition effect</em>'.
   * @see org.xtext.example.mydsl.arduino.transition_effect
   * @generated
   */
  EClass gettransition_effect();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.arduino.transition_effect#getMicroseconds <em>Microseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Microseconds</em>'.
   * @see org.xtext.example.mydsl.arduino.transition_effect#getMicroseconds()
   * @see #gettransition_effect()
   * @generated
   */
  EAttribute gettransition_effect_Microseconds();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.arduino.state <em>state</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>state</em>'.
   * @see org.xtext.example.mydsl.arduino.state
   * @generated
   */
  EClass getstate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.arduino.state#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.arduino.state#getName()
   * @see #getstate()
   * @generated
   */
  EAttribute getstate_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.arduino.state#getComponent <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Component</em>'.
   * @see org.xtext.example.mydsl.arduino.state#getComponent()
   * @see #getstate()
   * @generated
   */
  EReference getstate_Component();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.arduino.state#getComponent_state <em>Component state</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Component state</em>'.
   * @see org.xtext.example.mydsl.arduino.state#getComponent_state()
   * @see #getstate()
   * @generated
   */
  EReference getstate_Component_state();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ArduinoFactory getArduinoFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.arduino.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.arduino.impl.ModelImpl
     * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__COMPONENTS = eINSTANCE.getModel_Components();

    /**
     * The meta object literal for the '<em><b>Connection</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CONNECTION = eINSTANCE.getModel_Connection();

    /**
     * The meta object literal for the '<em><b>Behavior</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__BEHAVIOR = eINSTANCE.getModel_Behavior();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.arduino.impl.componentsImpl <em>components</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.arduino.impl.componentsImpl
     * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getcomponents()
     * @generated
     */
    EClass COMPONENTS = eINSTANCE.getcomponents();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENTS__NAME = eINSTANCE.getcomponents_Name();

    /**
     * The meta object literal for the '<em><b>Connectors</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENTS__CONNECTORS = eINSTANCE.getcomponents_Connectors();

    /**
     * The meta object literal for the '<em><b>Component state</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENTS__COMPONENT_STATE = eINSTANCE.getcomponents_Component_state();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.arduino.impl.component_stateImpl <em>component state</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.arduino.impl.component_stateImpl
     * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getcomponent_state()
     * @generated
     */
    EClass COMPONENT_STATE = eINSTANCE.getcomponent_state();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT_STATE__NAME = eINSTANCE.getcomponent_state_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.arduino.impl.minImpl <em>min</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.arduino.impl.minImpl
     * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getmin()
     * @generated
     */
    EClass MIN = eINSTANCE.getmin();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MIN__NAME = eINSTANCE.getmin_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.arduino.impl.maxImpl <em>max</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.arduino.impl.maxImpl
     * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getmax()
     * @generated
     */
    EClass MAX = eINSTANCE.getmax();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAX__NAME = eINSTANCE.getmax_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.arduino.impl.connectionImpl <em>connection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.arduino.impl.connectionImpl
     * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getconnection()
     * @generated
     */
    EClass CONNECTION = eINSTANCE.getconnection();

    /**
     * The meta object literal for the '<em><b>Component</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNECTION__COMPONENT = eINSTANCE.getconnection_Component();

    /**
     * The meta object literal for the '<em><b>Wiring</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNECTION__WIRING = eINSTANCE.getconnection_Wiring();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.arduino.impl.componentImpl <em>component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.arduino.impl.componentImpl
     * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getcomponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getcomponent();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__COMPONENTS = eINSTANCE.getcomponent_Components();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__NAME = eINSTANCE.getcomponent_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.arduino.impl.wiringImpl <em>wiring</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.arduino.impl.wiringImpl
     * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getwiring()
     * @generated
     */
    EClass WIRING = eINSTANCE.getwiring();

    /**
     * The meta object literal for the '<em><b>Src</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WIRING__SRC = eINSTANCE.getwiring_Src();

    /**
     * The meta object literal for the '<em><b>Src port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WIRING__SRC_PORT = eINSTANCE.getwiring_Src_port();

    /**
     * The meta object literal for the '<em><b>Tar</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WIRING__TAR = eINSTANCE.getwiring_Tar();

    /**
     * The meta object literal for the '<em><b>Tar port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WIRING__TAR_PORT = eINSTANCE.getwiring_Tar_port();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.arduino.impl.behaviorImpl <em>behavior</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.arduino.impl.behaviorImpl
     * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getbehavior()
     * @generated
     */
    EClass BEHAVIOR = eINSTANCE.getbehavior();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEHAVIOR__STATES = eINSTANCE.getbehavior_States();

    /**
     * The meta object literal for the '<em><b>Transitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEHAVIOR__TRANSITIONS = eINSTANCE.getbehavior_Transitions();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.arduino.impl.transitionImpl <em>transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.arduino.impl.transitionImpl
     * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#gettransition()
     * @generated
     */
    EClass TRANSITION = eINSTANCE.gettransition();

    /**
     * The meta object literal for the '<em><b>Src state</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__SRC_STATE = eINSTANCE.gettransition_Src_state();

    /**
     * The meta object literal for the '<em><b>Tar state</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__TAR_STATE = eINSTANCE.gettransition_Tar_state();

    /**
     * The meta object literal for the '<em><b>Transition effect</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__TRANSITION_EFFECT = eINSTANCE.gettransition_Transition_effect();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.arduino.impl.transition_effectImpl <em>transition effect</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.arduino.impl.transition_effectImpl
     * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#gettransition_effect()
     * @generated
     */
    EClass TRANSITION_EFFECT = eINSTANCE.gettransition_effect();

    /**
     * The meta object literal for the '<em><b>Microseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION_EFFECT__MICROSECONDS = eINSTANCE.gettransition_effect_Microseconds();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.arduino.impl.stateImpl <em>state</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.arduino.impl.stateImpl
     * @see org.xtext.example.mydsl.arduino.impl.ArduinoPackageImpl#getstate()
     * @generated
     */
    EClass STATE = eINSTANCE.getstate();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__NAME = eINSTANCE.getstate_Name();

    /**
     * The meta object literal for the '<em><b>Component</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__COMPONENT = eINSTANCE.getstate_Component();

    /**
     * The meta object literal for the '<em><b>Component state</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__COMPONENT_STATE = eINSTANCE.getstate_Component_state();

  }

} //ArduinoPackage
