/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.arduino;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>connection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.arduino.connection#getComponent <em>Component</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.arduino.connection#getWiring <em>Wiring</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.arduino.ArduinoPackage#getconnection()
 * @model
 * @generated
 */
public interface connection extends EObject
{
  /**
   * Returns the value of the '<em><b>Component</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.arduino.component}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component</em>' containment reference list.
   * @see org.xtext.example.mydsl.arduino.ArduinoPackage#getconnection_Component()
   * @model containment="true"
   * @generated
   */
  EList<component> getComponent();

  /**
   * Returns the value of the '<em><b>Wiring</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.arduino.wiring}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wiring</em>' containment reference list.
   * @see org.xtext.example.mydsl.arduino.ArduinoPackage#getconnection_Wiring()
   * @model containment="true"
   * @generated
   */
  EList<wiring> getWiring();

} // connection
