/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.arduino;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>state</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.arduino.state#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.arduino.state#getComponent <em>Component</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.arduino.state#getComponent_state <em>Component state</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.arduino.ArduinoPackage#getstate()
 * @model
 * @generated
 */
public interface state extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.arduino.ArduinoPackage#getstate_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.arduino.state#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Component</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component</em>' reference.
   * @see #setComponent(component)
   * @see org.xtext.example.mydsl.arduino.ArduinoPackage#getstate_Component()
   * @model
   * @generated
   */
  component getComponent();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.arduino.state#getComponent <em>Component</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Component</em>' reference.
   * @see #getComponent()
   * @generated
   */
  void setComponent(component value);

  /**
   * Returns the value of the '<em><b>Component state</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component state</em>' reference.
   * @see #setComponent_state(component_state)
   * @see org.xtext.example.mydsl.arduino.ArduinoPackage#getstate_Component_state()
   * @model
   * @generated
   */
  component_state getComponent_state();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.arduino.state#getComponent_state <em>Component state</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Component state</em>' reference.
   * @see #getComponent_state()
   * @generated
   */
  void setComponent_state(component_state value);

} // state
