/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.arduino;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.arduino.transition#getSrc_state <em>Src state</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.arduino.transition#getTar_state <em>Tar state</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.arduino.transition#getTransition_effect <em>Transition effect</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.arduino.ArduinoPackage#gettransition()
 * @model
 * @generated
 */
public interface transition extends EObject
{
  /**
   * Returns the value of the '<em><b>Src state</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Src state</em>' reference.
   * @see #setSrc_state(state)
   * @see org.xtext.example.mydsl.arduino.ArduinoPackage#gettransition_Src_state()
   * @model
   * @generated
   */
  state getSrc_state();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.arduino.transition#getSrc_state <em>Src state</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Src state</em>' reference.
   * @see #getSrc_state()
   * @generated
   */
  void setSrc_state(state value);

  /**
   * Returns the value of the '<em><b>Tar state</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tar state</em>' reference.
   * @see #setTar_state(state)
   * @see org.xtext.example.mydsl.arduino.ArduinoPackage#gettransition_Tar_state()
   * @model
   * @generated
   */
  state getTar_state();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.arduino.transition#getTar_state <em>Tar state</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tar state</em>' reference.
   * @see #getTar_state()
   * @generated
   */
  void setTar_state(state value);

  /**
   * Returns the value of the '<em><b>Transition effect</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transition effect</em>' containment reference.
   * @see #setTransition_effect(transition_effect)
   * @see org.xtext.example.mydsl.arduino.ArduinoPackage#gettransition_Transition_effect()
   * @model containment="true"
   * @generated
   */
  transition_effect getTransition_effect();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.arduino.transition#getTransition_effect <em>Transition effect</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transition effect</em>' containment reference.
   * @see #getTransition_effect()
   * @generated
   */
  void setTransition_effect(transition_effect value);

} // transition
