/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.arduino;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>transition effect</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.arduino.transition_effect#getMicroseconds <em>Microseconds</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.arduino.ArduinoPackage#gettransition_effect()
 * @model
 * @generated
 */
public interface transition_effect extends EObject
{
  /**
   * Returns the value of the '<em><b>Microseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Microseconds</em>' attribute.
   * @see #setMicroseconds(int)
   * @see org.xtext.example.mydsl.arduino.ArduinoPackage#gettransition_effect_Microseconds()
   * @model
   * @generated
   */
  int getMicroseconds();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.arduino.transition_effect#getMicroseconds <em>Microseconds</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Microseconds</em>' attribute.
   * @see #getMicroseconds()
   * @generated
   */
  void setMicroseconds(int value);

} // transition_effect
