/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.arduino;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>wiring</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.arduino.wiring#getSrc <em>Src</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.arduino.wiring#getSrc_port <em>Src port</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.arduino.wiring#getTar <em>Tar</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.arduino.wiring#getTar_port <em>Tar port</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.arduino.ArduinoPackage#getwiring()
 * @model
 * @generated
 */
public interface wiring extends EObject
{
  /**
   * Returns the value of the '<em><b>Src</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Src</em>' reference.
   * @see #setSrc(component)
   * @see org.xtext.example.mydsl.arduino.ArduinoPackage#getwiring_Src()
   * @model
   * @generated
   */
  component getSrc();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.arduino.wiring#getSrc <em>Src</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Src</em>' reference.
   * @see #getSrc()
   * @generated
   */
  void setSrc(component value);

  /**
   * Returns the value of the '<em><b>Src port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Src port</em>' attribute.
   * @see #setSrc_port(String)
   * @see org.xtext.example.mydsl.arduino.ArduinoPackage#getwiring_Src_port()
   * @model
   * @generated
   */
  String getSrc_port();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.arduino.wiring#getSrc_port <em>Src port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Src port</em>' attribute.
   * @see #getSrc_port()
   * @generated
   */
  void setSrc_port(String value);

  /**
   * Returns the value of the '<em><b>Tar</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tar</em>' reference.
   * @see #setTar(component)
   * @see org.xtext.example.mydsl.arduino.ArduinoPackage#getwiring_Tar()
   * @model
   * @generated
   */
  component getTar();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.arduino.wiring#getTar <em>Tar</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tar</em>' reference.
   * @see #getTar()
   * @generated
   */
  void setTar(component value);

  /**
   * Returns the value of the '<em><b>Tar port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tar port</em>' attribute.
   * @see #setTar_port(String)
   * @see org.xtext.example.mydsl.arduino.ArduinoPackage#getwiring_Tar_port()
   * @model
   * @generated
   */
  String getTar_port();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.arduino.wiring#getTar_port <em>Tar port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tar port</em>' attribute.
   * @see #getTar_port()
   * @generated
   */
  void setTar_port(String value);

} // wiring
