/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.arduino.ui.internal.ArduinoActivator;

public class ArduinoUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ArduinoActivator.getInstance().getInjector("org.xtext.example.mydsl.Arduino");
	}

}
